// ─────────────────────────────────────────────────────────────
//  NCERT Maths syllabus — chapters + subtopics, per class.
//  AUTO-GENERATED by backend/extract_syllabus.py from the ingested
//  NCERT PDFs. Do not hand-edit; re-run the extractor to regenerate.
//  Shape: SYLLABUS[class] = [{ id, num, title, subtopics:[{ id, num, title }] }]
// ─────────────────────────────────────────────────────────────

export interface Subtopic {
  id: string;
  num: string;
  title: string;
}

export interface SyllabusChapter {
  id: string;
  num: number;
  title: string;
  subtopics: Subtopic[];
}

export const SYLLABUS: Record<number, SyllabusChapter[]> = {
  6: [
    { id: 'g6-patterns-in-mathematics', num: 1, title: 'Patterns in Mathematics', subtopics: [
      { id: 'g6-patterns-in-mathematics-1-1', num: '1.1', title: 'What is Mathematics?' },
      { id: 'g6-patterns-in-mathematics-1-2', num: '1.2', title: 'Patterns in Numbers' },
      { id: 'g6-patterns-in-mathematics-1-3', num: '1.3', title: 'Visualising Number Sequences' },
      { id: 'g6-patterns-in-mathematics-1-4', num: '1.4', title: 'Relations among Number Sequences' },
      { id: 'g6-patterns-in-mathematics-1-5', num: '1.5', title: 'Patterns in Shapes' },
      { id: 'g6-patterns-in-mathematics-1-6', num: '1.6', title: 'Relation to Number Sequences' },
    ] },
    { id: 'g6-lines-and-angles', num: 2, title: 'Lines and Angles', subtopics: [
      { id: 'g6-lines-and-angles-2-1', num: '2.1', title: 'Point' },
      { id: 'g6-lines-and-angles-2-2', num: '2.2', title: 'Line Segment' },
      { id: 'g6-lines-and-angles-2-3', num: '2.3', title: 'Line' },
      { id: 'g6-lines-and-angles-2-4', num: '2.4', title: 'Ray' },
      { id: 'g6-lines-and-angles-2-5', num: '2.5', title: 'Angle' },
      { id: 'g6-lines-and-angles-2-6', num: '2.6', title: 'Comparing Angles' },
      { id: 'g6-lines-and-angles-2-7', num: '2.7', title: 'Making Rotating Arms' },
      { id: 'g6-lines-and-angles-2-8', num: '2.8', title: 'Special Types of Angles' },
      { id: 'g6-lines-and-angles-2-9', num: '2.9', title: 'Measuring Angles' },
      { id: 'g6-lines-and-angles-2-10', num: '2.10', title: 'Drawing Angles' },
      { id: 'g6-lines-and-angles-2-11', num: '2.11', title: 'Types of Angles and their Measures' },
    ] },
    { id: 'g6-number-play', num: 3, title: 'Number Play', subtopics: [
      { id: 'g6-number-play-3-1', num: '3.1', title: 'Numbers can Tell us Things' },
      { id: 'g6-number-play-3-2', num: '3.2', title: 'Supercells' },
      { id: 'g6-number-play-3-3', num: '3.3', title: 'Patterns of Numbers on the Number Line' },
      { id: 'g6-number-play-3-4', num: '3.4', title: 'Playing with Digits' },
      { id: 'g6-number-play-3-5', num: '3.5', title: 'Pretty Palindromic Patterns' },
      { id: 'g6-number-play-3-6', num: '3.6', title: 'The Magic Number of Kaprekar' },
      { id: 'g6-number-play-3-7', num: '3.7', title: 'Clock and Calendar Numbers' },
      { id: 'g6-number-play-3-8', num: '3.8', title: 'Mental Math' },
      { id: 'g6-number-play-3-9', num: '3.9', title: 'Playing with Number Patterns' },
      { id: 'g6-number-play-3-10', num: '3.10', title: 'An Unsolved Mystery — the Collatz Conjecture!' },
      { id: 'g6-number-play-3-11', num: '3.11', title: 'Simple Estimation' },
      { id: 'g6-number-play-3-12', num: '3.12', title: 'Games and Winning Strategies' },
    ] },
    { id: 'g6-data-handling-and-presentation', num: 4, title: 'Data Handling and Presentation', subtopics: [
      { id: 'g6-data-handling-and-presentation-4-1', num: '4.1', title: 'Collecting and Organising Data' },
      { id: 'g6-data-handling-and-presentation-4-2', num: '4.2', title: 'Pictographs' },
      { id: 'g6-data-handling-and-presentation-4-3', num: '4.3', title: 'Bar Graphs' },
      { id: 'g6-data-handling-and-presentation-4-4', num: '4.4', title: 'Drawing a Bar Graph' },
      { id: 'g6-data-handling-and-presentation-4-5', num: '4.5', title: 'Artistic and Aesthetic Considerations' },
    ] },
    { id: 'g6-prime-time', num: 5, title: 'Prime Time', subtopics: [
      { id: 'g6-prime-time-5-1', num: '5.1', title: 'Common Multiples and Common Factors' },
      { id: 'g6-prime-time-5-2', num: '5.2', title: 'Prime Numbers' },
      { id: 'g6-prime-time-5-3', num: '5.3', title: 'Co-prime numbers for safekeeping treasures' },
      { id: 'g6-prime-time-5-4', num: '5.4', title: 'Prime Factorisation' },
      { id: 'g6-prime-time-5-5', num: '5.5', title: 'Divisibility Tests' },
      { id: 'g6-prime-time-5-6', num: '5.6', title: 'Fun with numbers' },
    ] },
    { id: 'g6-perimeter-and-area', num: 6, title: 'Perimeter and Area', subtopics: [
      { id: 'g6-perimeter-and-area-6-1', num: '6.1', title: 'Perimeter' },
      { id: 'g6-perimeter-and-area-6-2', num: '6.2', title: 'Area' },
      { id: 'g6-perimeter-and-area-6-3', num: '6.3', title: 'Area of a Triangle' },
    ] },
    { id: 'g6-fractions', num: 7, title: 'Fractions', subtopics: [
      { id: 'g6-fractions-7-1', num: '7.1', title: 'Fractional Units and Equal Shares' },
      { id: 'g6-fractions-7-2', num: '7.2', title: 'Fractional Units as Parts of a Whole' },
      { id: 'g6-fractions-7-3', num: '7.3', title: 'Measuring Using Fractional Units' },
      { id: 'g6-fractions-7-4', num: '7.4', title: 'Marking Fraction Lengths on the Number Line' },
      { id: 'g6-fractions-7-5', num: '7.5', title: 'Mixed Fractions' },
      { id: 'g6-fractions-7-6', num: '7.6', title: 'Equivalent Fractions' },
      { id: 'g6-fractions-7-7', num: '7.7', title: 'Comparing Fractions' },
      { id: 'g6-fractions-7-8', num: '7.8', title: 'Addition and Subtraction of Fractions' },
      { id: 'g6-fractions-7-9', num: '7.9', title: 'A Pinch of History' },
    ] },
    { id: 'g6-playing-with-constructions', num: 8, title: 'Playing with Constructions', subtopics: [
      { id: 'g6-playing-with-constructions-8-1', num: '8.1', title: 'Artwork' },
      { id: 'g6-playing-with-constructions-8-2', num: '8.2', title: 'Squares and Rectangles' },
      { id: 'g6-playing-with-constructions-8-3', num: '8.3', title: 'Constructing Squares and Rectangles' },
      { id: 'g6-playing-with-constructions-8-4', num: '8.4', title: 'An Exploration in Rectangles' },
      { id: 'g6-playing-with-constructions-8-5', num: '8.5', title: 'Exploring Diagonals of Rectangles and Squares' },
      { id: 'g6-playing-with-constructions-8-6', num: '8.6', title: 'Points Equidistant from Two Given Points' },
    ] },
    { id: 'g6-symmetry', num: 9, title: 'Symmetry', subtopics: [
      { id: 'g6-symmetry-9-1', num: '9.1', title: 'Line of Symmetry' },
      { id: 'g6-symmetry-9-2', num: '9.2', title: 'Rotational Symmetry' },
    ] },
    { id: 'g6-the-other-side-of-zero', num: 10, title: 'The Other Side of Zero', subtopics: [
      { id: 'g6-the-other-side-of-zero-10-1', num: '10.1', title: 'Bela’s Building of Fun' },
      { id: 'g6-the-other-side-of-zero-10-2', num: '10.2', title: 'The Token Model' },
      { id: 'g6-the-other-side-of-zero-10-3', num: '10.3', title: 'Integers in Other Places' },
      { id: 'g6-the-other-side-of-zero-10-4', num: '10.4', title: 'Explorations with Integers' },
      { id: 'g6-the-other-side-of-zero-10-5', num: '10.5', title: 'A Pinch of History' },
    ] },
  ],
  7: [
    { id: 'g7-large-numbers-around-us', num: 1, title: 'Large Numbers Around Us', subtopics: [
      { id: 'g7-large-numbers-around-us-1-1', num: '1.1', title: 'A Lakh Varieties!' },
      { id: 'g7-large-numbers-around-us-1-2', num: '1.2', title: 'Land of Tens' },
      { id: 'g7-large-numbers-around-us-1-3', num: '1.3', title: 'Of Crores and Crores!' },
      { id: 'g7-large-numbers-around-us-1-4', num: '1.4', title: 'Exact and Approximate Values' },
      { id: 'g7-large-numbers-around-us-1-5', num: '1.5', title: 'Patterns in Products' },
      { id: 'g7-large-numbers-around-us-1-6', num: '1.6', title: 'Did You Ever Wonder…?' },
    ] },
    { id: 'g7-arithmetic-expressions', num: 2, title: 'Arithmetic Expressions', subtopics: [
      { id: 'g7-arithmetic-expressions-2-1', num: '2.1', title: 'Simple Expressions' },
      { id: 'g7-arithmetic-expressions-2-2', num: '2.2', title: 'Reading and Evaluating Complex Expressions' },
    ] },
    { id: 'g7-a-peek-beyond-the-point', num: 3, title: 'A Peek Beyond the Point', subtopics: [
      { id: 'g7-a-peek-beyond-the-point-3-1', num: '3.1', title: 'The Need for Smaller Units' },
      { id: 'g7-a-peek-beyond-the-point-3-2', num: '3.2', title: 'A Tenth Part' },
      { id: 'g7-a-peek-beyond-the-point-3-3', num: '3.3', title: 'A Hundredth Part' },
      { id: 'g7-a-peek-beyond-the-point-3-4', num: '3.4', title: 'Decimal Place Value' },
      { id: 'g7-a-peek-beyond-the-point-3-5', num: '3.5', title: 'Units of Measurement' },
      { id: 'g7-a-peek-beyond-the-point-3-6', num: '3.6', title: 'Locating and Comparing Decimals' },
      { id: 'g7-a-peek-beyond-the-point-3-7', num: '3.7', title: 'Addition and Subtraction of Decimals' },
      { id: 'g7-a-peek-beyond-the-point-3-8', num: '3.8', title: 'More on the Decimal System' },
    ] },
    { id: 'g7-expressions-using-letter-numbers', num: 4, title: 'Expressions Using Letter-numbers', subtopics: [
      { id: 'g7-expressions-using-letter-numbers-4-1', num: '4.1', title: 'The Notion of Letter-Numbers' },
      { id: 'g7-expressions-using-letter-numbers-4-2', num: '4.2', title: 'Revisiting Arithmetic Expressions' },
      { id: 'g7-expressions-using-letter-numbers-4-3', num: '4.3', title: 'Omission of the Multiplication Symbol in' },
      { id: 'g7-expressions-using-letter-numbers-4-4', num: '4.4', title: 'Simplification of Algebraic Expressions' },
      { id: 'g7-expressions-using-letter-numbers-4-5', num: '4.5', title: 'Pick Patterns and Reveal Relationships' },
    ] },
    { id: 'g7-parallel-and-intersecting-lines', num: 5, title: 'Parallel and Intersecting Lines', subtopics: [
      { id: 'g7-parallel-and-intersecting-lines-5-1', num: '5.1', title: 'Across the Line' },
      { id: 'g7-parallel-and-intersecting-lines-5-2', num: '5.2', title: 'Perpendicular Lines' },
      { id: 'g7-parallel-and-intersecting-lines-5-3', num: '5.3', title: 'Between Lines' },
      { id: 'g7-parallel-and-intersecting-lines-5-4', num: '5.4', title: 'Parallel and Perpendicular Lines in Paper' },
      { id: 'g7-parallel-and-intersecting-lines-5-5', num: '5.5', title: 'Transversals' },
      { id: 'g7-parallel-and-intersecting-lines-5-6', num: '5.6', title: 'Corresponding Angles' },
      { id: 'g7-parallel-and-intersecting-lines-5-7', num: '5.7', title: 'Drawing Parallel Lines' },
      { id: 'g7-parallel-and-intersecting-lines-5-8', num: '5.8', title: 'Alternate Angles' },
      { id: 'g7-parallel-and-intersecting-lines-5-9', num: '5.9', title: 'Parallel Illusions' },
    ] },
    { id: 'g7-number-play', num: 6, title: 'Number Play', subtopics: [
      { id: 'g7-number-play-6-1', num: '6.1', title: 'Numbers Tell us Things' },
      { id: 'g7-number-play-6-2', num: '6.2', title: 'Picking Parity' },
      { id: 'g7-number-play-6-3', num: '6.3', title: 'Some Explorations in Grids' },
      { id: 'g7-number-play-6-4', num: '6.4', title: 'Nature’s Favourite Sequence: The Virahāṅka–' },
      { id: 'g7-number-play-6-5', num: '6.5', title: 'Digits in Disguise' },
    ] },
    { id: 'g7-a-tale-of-three-intersecting-lines', num: 7, title: 'A Tale of Three Intersecting Lines', subtopics: [
      { id: 'g7-a-tale-of-three-intersecting-lines-7-1', num: '7.1', title: 'Equilateral Triangles' },
      { id: 'g7-a-tale-of-three-intersecting-lines-7-2', num: '7.2', title: 'Constructing a Triangle When its Sides are' },
      { id: 'g7-a-tale-of-three-intersecting-lines-7-3', num: '7.3', title: 'Construction of Triangles When Some Sides' },
      { id: 'g7-a-tale-of-three-intersecting-lines-7-4', num: '7.4', title: 'Constructions Related to Altitudes of Triangles' },
      { id: 'g7-a-tale-of-three-intersecting-lines-7-5', num: '7.5', title: 'Types of Triangles' },
    ] },
    { id: 'g7-working-with-fractions', num: 8, title: 'Working with Fractions', subtopics: [
      { id: 'g7-working-with-fractions-8-1', num: '8.1', title: 'Multiplication of Fractions' },
      { id: 'g7-working-with-fractions-8-2', num: '8.2', title: 'Division of Fractions' },
      { id: 'g7-working-with-fractions-8-3', num: '8.3', title: 'Some Problems Involving Fractions' },
    ] },
    { id: 'g7-geometric-twins', num: 9, title: 'Geometric Twins', subtopics: [
      { id: 'g7-geometric-twins-1-1', num: '1.1', title: 'Geometric Twins' },
      { id: 'g7-geometric-twins-1-2', num: '1.2', title: 'Congruence of Triangles' },
      { id: 'g7-geometric-twins-1-3', num: '1.3', title: 'Angles of Isosceles and Equilateral Triangles' },
    ] },
    { id: 'g7-operations-with-integers', num: 10, title: 'Operations with Integers', subtopics: [
      { id: 'g7-operations-with-integers-2-1', num: '2.1', title: 'A Quick Recap of Integers' },
      { id: 'g7-operations-with-integers-2-2', num: '2.2', title: 'Multiplication of Integers' },
    ] },
    { id: 'g7-finding-common-ground', num: 11, title: 'Finding Common Ground', subtopics: [
      { id: 'g7-finding-common-ground-3-1', num: '3.1', title: 'The Greatest of All' },
      { id: 'g7-finding-common-ground-3-2', num: '3.2', title: 'Least, but not Last!' },
      { id: 'g7-finding-common-ground-3-3', num: '3.3', title: 'Patterns, Properties, and a Pretty Procedure!' },
    ] },
    { id: 'g7-another-peek-beyond-the-point', num: 12, title: 'Another Peek Beyond the Point', subtopics: [
      { id: 'g7-another-peek-beyond-the-point-4-1', num: '4.1', title: 'A Quick Recap of Decimals' },
      { id: 'g7-another-peek-beyond-the-point-4-2', num: '4.2', title: 'Decimal Multiplication' },
      { id: 'g7-another-peek-beyond-the-point-4-3', num: '4.3', title: 'Decimal Division' },
      { id: 'g7-another-peek-beyond-the-point-4-4', num: '4.4', title: 'Look Before You Leap!' },
    ] },
    { id: 'g7-connecting-the-dots', num: 13, title: 'Connecting the Dots…', subtopics: [
      { id: 'g7-connecting-the-dots-5-1', num: '5.1', title: 'Of Questions and Statements' },
      { id: 'g7-connecting-the-dots-5-2', num: '5.2', title: 'Representative Values' },
      { id: 'g7-connecting-the-dots-5-3', num: '5.3', title: 'Visualising Data' },
      { id: 'g7-connecting-the-dots-5-4', num: '5.4', title: 'Data Detective' },
    ] },
    { id: 'g7-constructions-and-tilings', num: 14, title: 'Constructions and Tilings', subtopics: [
      { id: 'g7-constructions-and-tilings-6-1', num: '6.1', title: 'Geometric Constructions' },
      { id: 'g7-constructions-and-tilings-6-2', num: '6.2', title: 'Tiling' },
    ] },
    { id: 'g7-finding-the-unknown', num: 15, title: 'Finding the Unknown', subtopics: [
      { id: 'g7-finding-the-unknown-7-1', num: '7.1', title: 'Find the Unknowns' },
      { id: 'g7-finding-the-unknown-7-2', num: '7.2', title: 'Solving Equations Systematically' },
      { id: 'g7-finding-the-unknown-7-3', num: '7.3', title: 'Mind the Mistake, Mend the Mistake' },
      { id: 'g7-finding-the-unknown-7-4', num: '7.4', title: 'A Pinch of History' },
    ] },
  ],
  8: [
    { id: 'g8-a-square-and-a-cube', num: 1, title: 'A Square and a Cube', subtopics: [
      { id: 'g8-a-square-and-a-cube-1-1', num: '1.1', title: 'Square Numbers' },
      { id: 'g8-a-square-and-a-cube-1-2', num: '1.2', title: 'Cubic Numbers' },
      { id: 'g8-a-square-and-a-cube-1-3', num: '1.3', title: 'A Pinch of History' },
    ] },
    { id: 'g8-power-play', num: 2, title: 'Power Play', subtopics: [
      { id: 'g8-power-play-2-1', num: '2.1', title: 'Experiencing the Power Play ...' },
      { id: 'g8-power-play-2-2', num: '2.2', title: 'Exponential Notation and Operations' },
      { id: 'g8-power-play-2-3', num: '2.3', title: 'The Other Side of Powers' },
      { id: 'g8-power-play-2-4', num: '2.4', title: 'Powers of 10' },
      { id: 'g8-power-play-2-5', num: '2.5', title: 'Did You Ever Wonder?' },
    ] },
    { id: 'g8-a-story-of-numbers', num: 3, title: 'A Story of Numbers', subtopics: [
      { id: 'g8-a-story-of-numbers-3-1', num: '3.1', title: 'Reema’s Curiosity' },
      { id: 'g8-a-story-of-numbers-3-2', num: '3.2', title: 'Some Early Number Systems' },
      { id: 'g8-a-story-of-numbers-3-3', num: '3.3', title: 'The Idea of a Base' },
    ] },
    { id: 'g8-quadrilaterals', num: 4, title: 'Quadrilaterals', subtopics: [
      { id: 'g8-quadrilaterals-4-1', num: '4.1', title: 'Rectangles and Squares' },
      { id: 'g8-quadrilaterals-4-2', num: '4.2', title: 'Angles in a Quadrilateral' },
      { id: 'g8-quadrilaterals-4-3', num: '4.3', title: 'More Quadrilaterals with Parallel Opposite' },
      { id: 'g8-quadrilaterals-4-4', num: '4.4', title: 'Quadrilaterals with Equal Sidelengths' },
      { id: 'g8-quadrilaterals-4-5', num: '4.5', title: 'Playing with Quadrilaterals' },
      { id: 'g8-quadrilaterals-4-6', num: '4.6', title: 'Kite and Trapezium' },
    ] },
    { id: 'g8-number-play', num: 5, title: 'Number Play', subtopics: [
      { id: 'g8-number-play-5-1', num: '5.1', title: 'Is This a Multiple Of?' },
      { id: 'g8-number-play-5-2', num: '5.2', title: 'Checking Divisibility Quickly' },
      { id: 'g8-number-play-5-3', num: '5.3', title: 'Digits in Disguise' },
    ] },
    { id: 'g8-we-distribute-yet-things-multiply', num: 6, title: 'We Distribute, Yet Things Multiply', subtopics: [
      { id: 'g8-we-distribute-yet-things-multiply-6-1', num: '6.1', title: 'Some Properties of Multiplication' },
      { id: 'g8-we-distribute-yet-things-multiply-6-2', num: '6.2', title: 'Special Cases of the Distributive Property' },
      { id: 'g8-we-distribute-yet-things-multiply-6-3', num: '6.3', title: 'Mind the Mistake, Mend the Mistake' },
      { id: 'g8-we-distribute-yet-things-multiply-6-4', num: '6.4', title: 'This Way or That Way, All Ways Lead to the Bay' },
    ] },
    { id: 'g8-proportional-reasoning-1', num: 7, title: 'Proportional Reasoning-1', subtopics: [
      { id: 'g8-proportional-reasoning-1-7-1', num: '7.1', title: 'Observing Similarity in Change' },
      { id: 'g8-proportional-reasoning-1-7-2', num: '7.2', title: 'Ratios' },
      { id: 'g8-proportional-reasoning-1-7-3', num: '7.3', title: 'Ratios in their Simplest Form' },
      { id: 'g8-proportional-reasoning-1-7-4', num: '7.4', title: 'Problem Solving with Proportional Reasoning' },
      { id: 'g8-proportional-reasoning-1-7-5', num: '7.5', title: 'Sharing, but Not Equally!' },
      { id: 'g8-proportional-reasoning-1-7-6', num: '7.6', title: 'Unit Conversions' },
    ] },
    { id: 'g8-fractions-in-disguise', num: 8, title: 'Fractions in Disguise', subtopics: [
      { id: 'g8-fractions-in-disguise-1-1', num: '1.1', title: 'Fractions as Percentages' },
      { id: 'g8-fractions-in-disguise-1-2', num: '1.2', title: 'Percentage of Some Quantity' },
      { id: 'g8-fractions-in-disguise-1-3', num: '1.3', title: 'Using Percentages' },
    ] },
    { id: 'g8-the-baudhayana-pythagoras-theorem', num: 9, title: 'The Baudhāyana-pythagoras Theorem', subtopics: [
      { id: 'g8-the-baudhayana-pythagoras-theorem-2-1', num: '2.1', title: 'Doubling a Square' },
      { id: 'g8-the-baudhayana-pythagoras-theorem-2-2', num: '2.2', title: 'Halving a Square' },
      { id: 'g8-the-baudhayana-pythagoras-theorem-2-3', num: '2.3', title: 'Hypotenuse of an Isosceles Right Triangle' },
      { id: 'g8-the-baudhayana-pythagoras-theorem-2-4', num: '2.4', title: 'Combining Two Different Squares' },
      { id: 'g8-the-baudhayana-pythagoras-theorem-2-5', num: '2.5', title: 'Right–Triangles Having Integer Sidelengths' },
      { id: 'g8-the-baudhayana-pythagoras-theorem-2-6', num: '2.6', title: 'A Long-Standing Open Problem' },
      { id: 'g8-the-baudhayana-pythagoras-theorem-2-7', num: '2.7', title: 'Further Applications of the Baudhāyana -' },
    ] },
    { id: 'g8-proportional-reasoning2', num: 10, title: 'Proportional Reasoning–2', subtopics: [
      { id: 'g8-proportional-reasoning2-3-1', num: '3.1', title: 'Proportionality — A Quick Recap' },
      { id: 'g8-proportional-reasoning2-3-2', num: '3.2', title: 'Ratios in Maps' },
      { id: 'g8-proportional-reasoning2-3-3', num: '3.3', title: 'Ratios with More than 2 Terms' },
      { id: 'g8-proportional-reasoning2-3-4', num: '3.4', title: 'Dividing a Whole in a Given Ratio' },
      { id: 'g8-proportional-reasoning2-3-5', num: '3.5', title: 'A Slice of the Pie' },
      { id: 'g8-proportional-reasoning2-3-6', num: '3.6', title: 'Inverse Proportions' },
    ] },
    { id: 'g8-exploring-some-geometric-themes', num: 11, title: 'Exploring Some Geometric Themes', subtopics: [
      { id: 'g8-exploring-some-geometric-themes-4-1', num: '4.1', title: 'Fractals' },
      { id: 'g8-exploring-some-geometric-themes-4-2', num: '4.2', title: 'Visualising Solids' },
    ] },
    { id: 'g8-tales-by-dots-and-lines', num: 12, title: 'Tales by Dots and Lines', subtopics: [
      { id: 'g8-tales-by-dots-and-lines-5-1', num: '5.1', title: 'The Balancing Act' },
      { id: 'g8-tales-by-dots-and-lines-5-2', num: '5.2', title: 'Visualising and Interpreting Data' },
    ] },
    { id: 'g8-algebra-play', num: 13, title: 'Algebra Play', subtopics: [
      { id: 'g8-algebra-play-6-1', num: '6.1', title: 'Algebra Play' },
      { id: 'g8-algebra-play-6-2', num: '6.2', title: 'Thinking about ‘Think of a Number’ Tricks' },
      { id: 'g8-algebra-play-6-3', num: '6.3', title: 'Number Pyramids' },
      { id: 'g8-algebra-play-6-4', num: '6.4', title: 'Fun with Grids' },
      { id: 'g8-algebra-play-6-5', num: '6.5', title: 'The Largest Product' },
      { id: 'g8-algebra-play-6-6', num: '6.6', title: 'Decoding Divisibility Tricks' },
    ] },
    { id: 'g8-area', num: 14, title: 'Area', subtopics: [
      { id: 'g8-area-7-1', num: '7.1', title: 'Rectangle and Squares' },
    ] },
  ],
};

export const classChapters = (cls?: string | number): SyllabusChapter[] =>
  SYLLABUS[Number(cls)] || SYLLABUS[6];

export const chapterByIdC = (cls: string | number | undefined, id: string): SyllabusChapter | null =>
  classChapters(cls).find((c) => c.id === id) || null;

// ── Global (grade-agnostic) chapter resolver ──────────────────
// Chapter ids are class-prefixed (g6-…/g7-…/g8-…) so a single flat lookup
// works across all classes. This is the ONE source of truth for resolving a
// plan/session topic id → its title, number, grade and subtopics.
export interface ChapterRef extends SyllabusChapter { grade: number; }

const ALL_CHAPTERS: ChapterRef[] = Object.entries(SYLLABUS).flatMap(
  ([g, chs]) => chs.map((c) => ({ ...c, grade: Number(g) })),
);

export const chapterInfo = (id?: string | null): ChapterRef | null =>
  (id && ALL_CHAPTERS.find((c) => c.id === id)) || null;

export const chapterTitleById = (id?: string | null): string =>
  chapterInfo(id)?.title || '';

export const subtopicCount = (id?: string | null): number =>
  chapterInfo(id)?.subtopics.length || 0;
